# Generated by Django 5.0.6 on 2024-05-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('detailed_title', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
    ]
