# Generated by Django 5.0.6 on 2024-05-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr_museum_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Photo',
        ),
    ]
