# Generated by Django 5.0.6 on 2024-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_museum_app', '0002_rename_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='time',
            field=models.DateField(),
        ),
    ]
