# Generated by Django 5.0.6 on 2024-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_museum_app', '0003_alter_photo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='content',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
