# Generated by Django 5.0.6 on 2024-05-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_museum_app', '0004_alter_photo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='content',
            field=models.BinaryField(),
        ),
    ]
