# Generated by Django 4.2.5 on 2024-05-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_museum_app', '0010_photo_photo_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
